SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [PhysicianFacilityLink](
	[PhysicianID] [binary](16) NOT NULL,
	[FacilityID] [binary](16) NOT NULL,
	[Active] [bit] NOT NULL,
 CONSTRAINT [PK_PhysicianFacilityLink] PRIMARY KEY NONCLUSTERED 
(
	[PhysicianID] ASC,
	[FacilityID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
)

GO

SET ANSI_PADDING OFF
GO


CREATE NONCLUSTERED INDEX [IX_PhysicianFacilityLink_FacilityID] ON [PhysicianFacilityLink] 
(
	[FacilityID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
GO


CREATE NONCLUSTERED INDEX [IX_PhysicianFacilityLink_PhysicianID] ON [PhysicianFacilityLink] 
(
	[PhysicianID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
GO

ALTER TABLE [PhysicianFacilityLink] ADD  CONSTRAINT [DF_PhysicianFacilityLink_Active]  DEFAULT ((1)) FOR [Active]
GO

