SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [ProcedureFacilityLink](
	[ProcedureID] [binary](16) NOT NULL,
	[FacilityID] [binary](16) NOT NULL,
	[Active] [bit] NOT NULL,
 CONSTRAINT [PK_ProcedureFacilityLink] PRIMARY KEY NONCLUSTERED 
(
	[ProcedureID] ASC,
	[FacilityID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
)

GO

SET ANSI_PADDING OFF
GO


CREATE NONCLUSTERED INDEX [IX_ProcedureFacilityLink_FacilityID] ON [ProcedureFacilityLink] 
(
	[FacilityID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
GO


CREATE NONCLUSTERED INDEX [IX_ProcedureFacilityLink_ProcedureID] ON [ProcedureFacilityLink] 
(
	[ProcedureID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
GO

ALTER TABLE [ProcedureFacilityLink] ADD  CONSTRAINT [DF_ProcedureFacilityLink_Active]  DEFAULT ((1)) FOR [Active]
GO

