SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [Procedures](
	[ID] [binary](16) NOT NULL,
	[Name] [nvarchar](64) NOT NULL,
	[TypeID] [binary](16) NOT NULL,
	[Duration] [smallint] NOT NULL,
	[Lead] [smallint] NOT NULL,
	[Custom] [bit] NOT NULL,
	[CommonName] [nvarchar](256) NULL,
	[ShortDesc] [nvarchar](256) NULL,
 CONSTRAINT [PK_Procedures_ID] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
)

GO

SET ANSI_PADDING OFF
GO


CREATE NONCLUSTERED INDEX [IX_Procedures_Name] ON [Procedures] 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
GO

ALTER TABLE [Procedures] ADD  CONSTRAINT [DF_Procedures_Custom]  DEFAULT ((0)) FOR [Custom]
GO

