SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [Babies](
	[ID] [binary](16) NOT NULL,
	[UserID] [binary](16) NOT NULL,
	[Name] [nvarchar](64) NULL,
	[Gender] [varchar](1) NULL,
 CONSTRAINT [PK_Babies] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [Babies] DISABLE CHANGE_TRACKING 
GO

SET ANSI_PADDING OFF
GO


CREATE NONCLUSTERED INDEX [IX_Babies_UserID] ON [Babies] 
(
	[UserID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

ALTER TABLE [Babies] ADD  CONSTRAINT [DF_Babies_Male]  DEFAULT ((0)) FOR [Gender]
GO

