SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [Checkitems](
	[ID] [binary](16) NOT NULL,
	[ChecklistID] [binary](16) NOT NULL,
	[Text] [nvarchar](512) NOT NULL,
	[OrderSeq] [int] NOT NULL,
	[Link] [nvarchar](512) NULL,
 CONSTRAINT [PK_Checkitems] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [Checkitems] DISABLE CHANGE_TRACKING 
GO

SET ANSI_PADDING OFF
GO


CREATE CLUSTERED INDEX [IX_Checkitems_ChecklistID] ON [Checkitems] 
(
	[ChecklistID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

