/****** Object:  Table [JournalEntries]    Script Date: 10/08/2012 21:11:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [JournalEntries](
	[ID] [binary](16) NOT NULL,
	[UserID] [binary](16) NOT NULL, 
	[Text] [nvarchar](512) NULL,
	[HasPhoto] [bit] NOT NULL, 
	[Created] [bigint] NOT NULL
	
  CONSTRAINT [PK_JournalEntries] PRIMARY KEY NONCLUSTERED 
  (
	  [ID] ASC
  ) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
)

GO

SET ANSI_PADDING OFF
GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_JournalEntries_Created] ON [JournalEntries] 
(
	[Created] DESC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
GO

CREATE NONCLUSTERED INDEX [IX_JournalEntries_UserID] ON [JournalEntries] 
(
	[UserID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
GO

ALTER TABLE [JournalEntries] ADD CONSTRAINT [DF_JournalEntries_HasPhoto]  DEFAULT ((0)) FOR [HasPhoto]
GO