SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [MeasureRecords](
	[ID] [binary](16) NOT NULL,
	[UserID] [binary](16) NOT NULL, 
	[BabyID] [binary](16) NULL, 
	[MeasureID] [binary](16) NOT NULL, 
	[Value] [numeric](28, 8) NULL,
	[Metric] [bit] NOT NULL, 
	[CreatedDate] [bigint] NOT NULL, 
 CONSTRAINT [PK_MeasureRecords] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
)

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [MeasureRecords] ADD CONSTRAINT [DF_MeasureRecords_Metric]  DEFAULT ((0)) FOR [Metric]
GO

CREATE NONCLUSTERED INDEX [IX_MeasureRecords_UserID] ON [MeasureRecords] 
(
	[UserID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
GO

CREATE NONCLUSTERED INDEX [IX_MeasureRecords_BabyID] ON [MeasureRecords] 
(
	[BabyID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
GO

CREATE NONCLUSTERED INDEX [IX_MeasureRecords_MeasureID] ON [MeasureRecords] 
(
	[MeasureID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
GO
