SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [Mothers](
	[ID] [binary](16) NOT NULL,
	[UserID] [binary](16) NOT NULL,
	[DueDate] [bigint] NULL,
	[BirthDate] [bigint] NULL,
	[Metric] [bit] NOT NULL,
	[Region] [nvarchar](64) NULL,
	[MedicalCenter] [nvarchar](64) NULL,
 CONSTRAINT [PK_Mothers] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
)

GO

SET ANSI_PADDING OFF
GO


CREATE UNIQUE NONCLUSTERED INDEX [IX_Mothers_UserID] ON [Mothers] 
(
	[UserID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
GO

ALTER TABLE [Mothers] ADD  CONSTRAINT [DF_Patients_MetricUnits]  DEFAULT ((0)) FOR [Metric]
GO

