/****** Object:  Table [Equipments]    Script Date: 09/09/2012 13:48:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [Equipments](
	[ID] [binary](16) NOT NULL,
	[Name] [nvarchar](32) NOT NULL,
	[Industry] [nvarchar](32) NULL, 
	[Weight] [int] NOT NULL
 CONSTRAINT [PK_Equipments] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
)

GO

SET ANSI_PADDING OFF
GO


CREATE UNIQUE NONCLUSTERED INDEX [IX_Equipments_Name] ON [Equipments] 
(
	[Name] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
GO

ALTER TABLE [Equipments] ADD  CONSTRAINT [DF_Equipments_Weight]  DEFAULT ((0)) FOR [Weight]
GO
