SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [Images](
	[ID] [binary](16) NOT NULL,
	[Width] [int] NOT NULL,
	[Height] [int] NOT NULL,
	[Version] [int] NOT NULL,
	[LengthBytes] [int] NOT NULL,
	[Bytes] [image] NOT NULL,
	[MimeType] [nvarchar](64) NOT NULL,
	[LinkedID] [binary](16) NOT NULL,
	[Name] [nvarchar](64) NOT NULL,
	[OriginalID] [binary](16) NOT NULL,
	[Size] [varchar](32) NOT NULL,
 CONSTRAINT [PK_Images] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
)

GO

SET ANSI_PADDING OFF
GO


CREATE UNIQUE NONCLUSTERED INDEX [IX_Images_LinkedID_Name] ON [Images] 
(
	[LinkedID] ASC,
	[Name] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
GO


CREATE UNIQUE NONCLUSTERED INDEX [IX_Images_OriginalID_Size] ON [Images] 
(
	[OriginalID] ASC,
	[Size] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
GO

ALTER TABLE [Images] ADD  CONSTRAINT [DF_Images_Width]  DEFAULT ((0)) FOR [Width]
GO

ALTER TABLE [Images] ADD  CONSTRAINT [DF_Images_Height]  DEFAULT ((0)) FOR [Height]
GO

ALTER TABLE [Images] ADD  CONSTRAINT [DF_Images_Version]  DEFAULT ((0)) FOR [Version]
GO

ALTER TABLE [Images] ADD  CONSTRAINT [DF_Images_SizeBytes]  DEFAULT ((0)) FOR [LengthBytes]
GO

