SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [Notifications](
	[ID] [binary](16) NOT NULL,
	[EventID] [binary](16) NOT NULL,
	[UserID] [binary](16) NOT NULL,
	[Channel] [nvarchar](8) NOT NULL,
	[Created] [bigint] NOT NULL,
	[StatusDate] [bigint] NOT NULL,
	[StatusCode] [smallint] NOT NULL,
	[FailCount] [int] NOT NULL,
	[ExternalID] [nvarchar](64) NULL,
	[Actionable] [smallint] NOT NULL,
 CONSTRAINT [PK_Notifications] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
)

GO

SET ANSI_PADDING OFF
GO


CREATE NONCLUSTERED INDEX [IX_Notifications_EventID] ON [Notifications] 
(
	[EventID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
GO


CREATE NONCLUSTERED INDEX [IX_Notifications_ExternalID] ON [Notifications] 
(
	[ExternalID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
GO


CREATE NONCLUSTERED INDEX [IX_Notifications_Status] ON [Notifications] 
(
	[StatusDate] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
GO


CREATE NONCLUSTERED INDEX [IX_Notifications_UserID] ON [Notifications] 
(
	[UserID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
GO

ALTER TABLE [Notifications] ADD  CONSTRAINT [DF_Notifications_StatusCode]  DEFAULT ((0)) FOR [StatusCode]
GO

ALTER TABLE [Notifications] ADD  CONSTRAINT [DF_Notifications_FailCount]  DEFAULT ((0)) FOR [FailCount]
GO

ALTER TABLE [Notifications] ADD  CONSTRAINT [DF_Notifications_Actionable]  DEFAULT ((0)) FOR [Actionable]
GO

