SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [Users](
	[ID] [binary](16) NOT NULL,
	[LoginName] [nvarchar](64) NOT NULL,
	[Password] [nvarchar](64) NOT NULL,
	[Email] [nvarchar](256) NOT NULL,
	[Name] [nvarchar](128) NOT NULL,
	[Joined] [bigint] NOT NULL,
	[LastActive] [bigint] NULL,
	[Suspended] [bit] NOT NULL,
	[Terminated] [bit] NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
)

GO

SET ANSI_PADDING OFF
GO


CREATE NONCLUSTERED INDEX [IX_Users_Email] ON [Users] 
(
	[Email] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
GO


CREATE NONCLUSTERED INDEX [IX_Users_UserName] ON [Users] 
(
	[LoginName] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
GO

ALTER TABLE [Users] ADD  CONSTRAINT [DF_Users_Suspended]  DEFAULT ((0)) FOR [Suspended]
GO

ALTER TABLE [Users] ADD  CONSTRAINT [DF_Users_Terminated]  DEFAULT ((0)) FOR [Terminated]
GO

